Repository elastic/package-storage, pull requests merged in 2021-02, with the labels that each got.

#837 feat: send a slack message after deploys
  .ci/release.groovy
Labels: Team:Automation, [zube]: In Review, automation, ci, enhancement

#846 fix: remove post in post
  .ci/release.groovy
Labels: Team:Automation, automation, bug, ci

#848 fix: move post a level up
  .ci/release.groovy
Labels: Team:Automation, automation, bug, ci

#849 fix: use the param instead the environment variable
  .ci/release.groovy
Labels: Team:Automation, automation, bug, ci

#839 updates for clarity and branches v testing nuances
  README.md
Labels: Team:Fleet

#919 Remove citrix package
  packages/citrix/0.2.2/data_stream/netscaler/agent/stream/stream.yml.hbs
  packages/citrix/0.2.2/data_stream/netscaler/agent/stream/tcp.yml.hbs
  packages/citrix/0.2.2/data_stream/netscaler/agent/stream/udp.yml.hbs
  packages/citrix/0.2.2/data_stream/netscaler/elasticsearch/ingest_pipeline/default.yml
  packages/citrix/0.2.2/data_stream/netscaler/fields/base-fields.yml
  packages/citrix/0.2.2/data_stream/netscaler/fields/ecs.yml
  packages/citrix/0.2.2/data_stream/netscaler/fields/fields.yml
  packages/citrix/0.2.2/data_stream/netscaler/manifest.yml
  packages/citrix/0.2.2/docs/README.md
  packages/citrix/0.2.2/img/logo.svg
  packages/citrix/0.2.2/manifest.yml
Labels: Team:Integrations

#939 ci: grab deploy info an archive it
  .ci/release.groovy
Labels: Team:Automation, automation, ci, enhancement

#943 ci: remove -i from the docker command
  .ci/release.groovy
Labels: Team:Automation, automation, bug, ci
