Repository elastic/package-storage, pull requests merged in 2022-07, with the labels that each got.

#4820 Publish apm-8.3.2
  packages/apm/8.3.2/agent/input/template.yml.hbs
  packages/apm/8.3.2/manifest.yml
Labels: automation

#4844 [httpjson] Remove defaults from manifest.
  packages/httpjson/1.3.1/changelog.yml
  packages/httpjson/1.3.1/data_stream/generic/agent/stream/httpjson.yml.hbs
  packages/httpjson/1.3.1/data_stream/generic/fields/base-fields.yml
  packages/httpjson/1.3.1/data_stream/generic/fields/beats.yml
  packages/httpjson/1.3.1/data_stream/generic/fields/ecs.yml
  packages/httpjson/1.3.1/data_stream/generic/manifest.yml
  packages/httpjson/1.3.1/data_stream/generic/sample_event.json
  packages/httpjson/1.3.1/docs/README.md
  packages/httpjson/1.3.1/manifest.yml
Labels: bug, Team:Security-External Integrations

#4878 Publish apm-8.4.0
  packages/apm/8.4.0/agent/input/template.yml.hbs
  packages/apm/8.4.0/changelog.yml
  packages/apm/8.4.0/data_stream/internal_metrics/fields/faas_metrics.yml
  packages/apm/8.4.0/data_stream/internal_metrics/fields/fields.yml
  packages/apm/8.4.0/docs/README.md
  packages/apm/8.4.0/manifest.yml
Labels: automation

#4880 Publish apm-8.2.4
  packages/apm/8.2.4/changelog.yml
  packages/apm/8.2.4/manifest.yml
Labels: automation

#4882 Publish apm-8.3.3
  packages/apm/8.3.3/changelog.yml
Labels: automation

#4928 Publish apm-8.4.0
  packages/apm/8.4.0/changelog.yml
  packages/apm/8.4.0/manifest.yml
Labels: automation

#4972 Publish apm-8.4.0
  packages/apm/8.4.0/changelog.yml
  packages/apm/8.4.0/img/apm-01-service-inventory.png
  packages/apm/8.4.0/img/apm-02-service-overview.png
  packages/apm/8.4.0/img/apm-03-trace.png
  packages/apm/8.4.0/img/apm-04-service-map.png
Labels: automation

#4982 Publish apm-8.3.3
  packages/apm/8.3.3/changelog.yml
  packages/apm/8.3.3/manifest.yml
Labels: automation

#4998 Publish apm-8.3.3
  packages/apm/8.3.3/changelog.yml
  packages/apm/8.3.3/img/apm-01-service-inventory.png
  packages/apm/8.3.3/img/apm-02-service-overview.png
  packages/apm/8.3.3/img/apm-03-trace.png
  packages/apm/8.3.3/img/apm-04-service-map.png
Labels: automation

#5046 [snapshot] Update Package Registry to v1.11.0
  Dockerfile
  go.mod
  go.sum
Labels: Team:Ecosystem
