Repository elastic/package-storage, pull requests merged in 2022-01, with the labels that each got.

#3252 [staging] Promote packages from snapshot (cisco_ios-1.3.0, symantec_endpoint-0.0.1)
  packages/cisco_ios/1.3.0/changelog.yml
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/agent.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/base-fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/ecs.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/manifest.yml
  packages/cisco_ios/1.3.0/data_stream/log/sample_event.json
  packages/cisco_ios/1.3.0/docs/README.md
  packages/cisco_ios/1.3.0/img/cisco.svg
  packages/cisco_ios/1.3.0/manifest.yml
  packages/symantec_endpoint/0.0.1/changelog.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/logfile.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/tcp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/udp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/agent.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/base-fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/ecs.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/manifest.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/sample_event.json
  packages/symantec_endpoint/0.0.1/docs/README.md
  packages/symantec_endpoint/0.0.1/img/logo.svg
  packages/symantec_endpoint/0.0.1/img/symantec-endpoint-logs-overview.png
  packages/symantec_endpoint/0.0.1/kibana/dashboard/symantec_endpoint-3ac0a690-5f71-11ec-85e4-338fc80d8393.json
  packages/symantec_endpoint/0.0.1/manifest.yml
Labels: Team:Security-External Integrations

#3254 Deprecate rsa2elk package for Symantec
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/stream.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/tcp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/udp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/elasticsearch/ingest_pipeline/default.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/base-fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/ecs.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/manifest.yml
  packages/symantec/0.1.3/docs/README.md
  packages/symantec/0.1.3/img/logo.svg
  packages/symantec/0.1.3/manifest.yml
Labels: Team:Security-External Integrations

#3253 [snapshot] Remove promoted packages (cisco_ios-1.3.0, symantec_endpoint-0.0.1)
  packages/cisco_ios/1.3.0/changelog.yml
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/agent.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/base-fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/ecs.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/manifest.yml
  packages/cisco_ios/1.3.0/data_stream/log/sample_event.json
  packages/cisco_ios/1.3.0/docs/README.md
  packages/cisco_ios/1.3.0/img/cisco.svg
  packages/cisco_ios/1.3.0/manifest.yml
  packages/symantec_endpoint/0.0.1/changelog.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/logfile.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/tcp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/udp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/agent.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/base-fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/ecs.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/manifest.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/sample_event.json
  packages/symantec_endpoint/0.0.1/docs/README.md
  packages/symantec_endpoint/0.0.1/img/logo.svg
  packages/symantec_endpoint/0.0.1/img/symantec-endpoint-logs-overview.png
  packages/symantec_endpoint/0.0.1/kibana/dashboard/symantec_endpoint-3ac0a690-5f71-11ec-85e4-338fc80d8393.json
  packages/symantec_endpoint/0.0.1/manifest.yml
Labels: Team:Security-External Integrations

#3257 [production] Promote packages from staging (cisco_ios-1.3.0, symantec_endpoint-0.0.1, symantec-0.1.3)
  packages/cisco_ios/1.3.0/changelog.yml
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/agent.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/base-fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/ecs.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/manifest.yml
  packages/cisco_ios/1.3.0/data_stream/log/sample_event.json
  packages/cisco_ios/1.3.0/docs/README.md
  packages/cisco_ios/1.3.0/img/cisco.svg
  packages/cisco_ios/1.3.0/manifest.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/stream.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/tcp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/udp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/elasticsearch/ingest_pipeline/default.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/base-fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/ecs.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/manifest.yml
  packages/symantec/0.1.3/docs/README.md
  packages/symantec/0.1.3/img/logo.svg
  packages/symantec/0.1.3/manifest.yml
  packages/symantec_endpoint/0.0.1/changelog.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/logfile.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/tcp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/udp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/agent.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/base-fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/ecs.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/manifest.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/sample_event.json
  packages/symantec_endpoint/0.0.1/docs/README.md
  packages/symantec_endpoint/0.0.1/img/logo.svg
  packages/symantec_endpoint/0.0.1/img/symantec-endpoint-logs-overview.png
  packages/symantec_endpoint/0.0.1/kibana/dashboard/symantec_endpoint-3ac0a690-5f71-11ec-85e4-338fc80d8393.json
  packages/symantec_endpoint/0.0.1/manifest.yml
Labels: Team:Security-External Integrations

#3258 [staging] Remove promoted packages (cisco_ios-1.3.0, symantec-0.1.3, symantec_endpoint-0.0.1)
  packages/cisco_ios/1.3.0/changelog.yml
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/1.3.0/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/agent.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/base-fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/ecs.yml
  packages/cisco_ios/1.3.0/data_stream/log/fields/fields.yml
  packages/cisco_ios/1.3.0/data_stream/log/manifest.yml
  packages/cisco_ios/1.3.0/data_stream/log/sample_event.json
  packages/cisco_ios/1.3.0/docs/README.md
  packages/cisco_ios/1.3.0/img/cisco.svg
  packages/cisco_ios/1.3.0/manifest.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/stream.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/tcp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/agent/stream/udp.yml.hbs
  packages/symantec/0.1.3/data_stream/endpointprotection/elasticsearch/ingest_pipeline/default.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/base-fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/ecs.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/fields/fields.yml
  packages/symantec/0.1.3/data_stream/endpointprotection/manifest.yml
  packages/symantec/0.1.3/docs/README.md
  packages/symantec/0.1.3/img/logo.svg
  packages/symantec/0.1.3/manifest.yml
  packages/symantec_endpoint/0.0.1/changelog.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/logfile.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/tcp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/agent/stream/udp.yml.hbs
  packages/symantec_endpoint/0.0.1/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/agent.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/base-fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/ecs.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/fields/fields.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/manifest.yml
  packages/symantec_endpoint/0.0.1/data_stream/log/sample_event.json
  packages/symantec_endpoint/0.0.1/docs/README.md
  packages/symantec_endpoint/0.0.1/img/logo.svg
  packages/symantec_endpoint/0.0.1/img/symantec-endpoint-logs-overview.png
  packages/symantec_endpoint/0.0.1/kibana/dashboard/symantec_endpoint-3ac0a690-5f71-11ec-85e4-338fc80d8393.json
  packages/symantec_endpoint/0.0.1/manifest.yml
Labels: Team:Security-External Integrations

#3302 Neutral naming for package-storage
  .ci/jobs/package-storage.yml
  .ci/jobs/release.yml
  README.md
Labels: automation

#3401 [snapshot] Package registry 1.6.0
  .go-version
  Dockerfile
  go.mod
  go.sum
Labels: Team:Ecosystem

#3405 [staging] Package registry 1.6.0
  .go-version
  Dockerfile
  go.mod
  go.sum
Labels: Team:Ecosystem

#3411 staging: Add apm `7.17.0-dev1` package
  packages/apm/7.17-dev1/agent/input/template.yml.hbs
  packages/apm/7.17-dev1/changelog.yml
  packages/apm/7.17-dev1/data_stream/app_logs/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/app_logs/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/app_logs/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/app_logs/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/app_logs/manifest.yml
  packages/apm/7.17-dev1/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/app_metrics/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/app_metrics/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/app_metrics/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/app_metrics/manifest.yml
  packages/apm/7.17-dev1/data_stream/error_logs/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/error_logs/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/error_logs/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/error_logs/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/error_logs/manifest.yml
  packages/apm/7.17-dev1/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/internal_metrics/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/internal_metrics/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/internal_metrics/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/internal_metrics/manifest.yml
  packages/apm/7.17-dev1/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/profile_metrics/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/profile_metrics/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/profile_metrics/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/profile_metrics/manifest.yml
  packages/apm/7.17-dev1/data_stream/sampled_traces/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/sampled_traces/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/sampled_traces/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/sampled_traces/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/sampled_traces/manifest.yml
  packages/apm/7.17-dev1/data_stream/traces/elasticsearch/ilm/default_policy.json
  packages/apm/7.17-dev1/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.yml
  packages/apm/7.17-dev1/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  packages/apm/7.17-dev1/data_stream/traces/fields/base-fields.yml
  packages/apm/7.17-dev1/data_stream/traces/fields/ecs.yml
  packages/apm/7.17-dev1/data_stream/traces/fields/fields.yml
  packages/apm/7.17-dev1/data_stream/traces/manifest.yml
  packages/apm/7.17-dev1/docs/README.md
  packages/apm/7.17-dev1/img/apm-01-service-inventory.png
  packages/apm/7.17-dev1/img/apm-02-service-overview.png
  packages/apm/7.17-dev1/img/apm-03-trace.png
  packages/apm/7.17-dev1/img/apm-04-service-map.png
  packages/apm/7.17-dev1/img/logo_apm.svg
  packages/apm/7.17-dev1/manifest.yml
Labels: v7.17.0
